// ============================================
// HTML EXPORTER - تصدير التقارير إلى HTML
// يدعم: قوالب HTML، CSS مدمج، عرض متجاوب
// ============================================

export class HTMLExporter {
    constructor() {
        this.templates = new Map();
        this.defaultTemplate = null;
        
        // تحميل القالب الافتراضي
        this.loadDefaultTemplate();
        
        console.log('🌐 HTMLExporter initialized');
    }
    
    loadDefaultTemplate() {
        this.defaultTemplate = `
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: #f0f2f5;
            padding: 20px;
            direction: rtl;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #1a1a2e, #16213e);
            color: white;
            padding: 30px;
            text-align: center;
        }
        .header h1 { font-size: 28px; margin-bottom: 10px; }
        .header .date { opacity: 0.8; font-size: 14px; }
        .summary-cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            padding: 30px;
            background: #f8f9fa;
        }
        .card {
            background: white;
            padding: 20px;
            border-radius: 10px;
            text-align: center;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        .card .value { font-size: 32px; font-weight: bold; color: #1a1a2e; }
        .card .label { color: #666; margin-top: 5px; font-size: 14px; }
        .content { padding: 30px; }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 12px;
            text-align: right;
            border-bottom: 1px solid #ddd;
        }
        th {
            background: #1a1a2e;
            color: white;
            font-weight: 600;
        }
        tr:hover { background: #f5f5f5; }
        .status-badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: bold;
        }
        .status-high { background: #ff4444; color: white; }
        .status-medium { background: #ffaa44; color: white; }
        .status-low { background: #44ff44; color: #333; }
        .footer {
            background: #f8f9fa;
            padding: 20px;
            text-align: center;
            color: #666;
            font-size: 12px;
            border-top: 1px solid #ddd;
        }
        @media (max-width: 768px) {
            .summary-cards { grid-template-columns: repeat(2, 1fr); }
            .container { margin: 10px; }
            th, td { padding: 8px; font-size: 12px; }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{{title}}</h1>
            <div class="date">{{date}}</div>
        </div>
        
        <div class="summary-cards">
            {{summaryCards}}
        </div>
        
        <div class="content">
            {{content}}
        </div>
        
        <div class="footer">
            Generated by Actual View Engine - {{generatedAt}}
        </div>
    </div>
</body>
</html>
        `;
    }
    
    // ========== MAIN EXPORT ==========
    
    exportToHTML(data, options = {}) {
        const template = options.template || this.defaultTemplate;
        const title = options.title || 'Report';
        
        let html = template;
        
        // استبدال المتغيرات
        html = html.replace(/{{title}}/g, title);
        html = html.replace(/{{date}}/g, new Date().toLocaleDateString('ar-EG'));
        html = html.replace(/{{generatedAt}}/g, new Date().toLocaleString('ar-EG'));
        
        // إضافة بطاقات الملخص
        if (data.summary) {
            let summaryHtml = '';
            for (const [key, value] of Object.entries(data.summary)) {
                summaryHtml += `
                    <div class="card">
                        <div class="value">${value}</div>
                        <div class="label">${this.formatLabel(key)}</div>
                    </div>
                `;
            }
            html = html.replace(/{{summaryCards}}/g, summaryHtml);
        } else {
            html = html.replace(/{{summaryCards}}/g, '');
        }
        
        // إضافة المحتوى الرئيسي
        let contentHtml = '';
        
        if (data.type === 'clash_report') {
            contentHtml = this.generateClashContent(data);
        } else if (data.type === 'boq_report') {
            contentHtml = this.generateBOQContent(data);
        } else if (data.tasks) {
            contentHtml = this.generateTasksContent(data.tasks);
        } else if (data.issues) {
            contentHtml = this.generateIssuesContent(data.issues);
        } else if (Array.isArray(data)) {
            contentHtml = this.generateTableContent(data);
        } else {
            contentHtml = `<pre>${JSON.stringify(data, null, 2)}</pre>`;
        }
        
        html = html.replace(/{{content}}/g, contentHtml);
        
        return html;
    }
    
    generateClashContent(data) {
        const clashes = data.clashes || [];
        
        let table = '<h2>Clash Detection Report</h2>';
        table += '<table><thead><tr>';
        table += '<th>ID</th><th>Type</th><th>Severity</th><th>Element A</th><th>Element B</th><th>Location</th>';
        table += '</tr></thead><tbody>';
        
        for (const clash of clashes) {
            const severityClass = `status-${clash.severity?.level || 'medium'}`;
            table += `<tr>
                <td>${clash.id?.slice(-8) || '-'}</td>
                <td>${clash.type || 'intersection'}</td>
                <td><span class="status-badge ${severityClass}">${clash.severity?.level || 'medium'}</span></td>
                <td>${clash.elementA?.name || clash.elementA?.id || '-'}</td>
                <td>${clash.elementB?.name || clash.elementB?.id || '-'}</td>
                <td>${clash.point ? `${clash.point.x.toFixed(1)}, ${clash.point.y.toFixed(1)}` : '-'}</td>
            </tr>`;
        }
        
        table += '</tbody></table>';
        return table;
    }
    
    generateBOQContent(data) {
        const items = data.items || [];
        let total = 0;
        
        let table = '<h2>Bill of Quantities (BOQ)</h2>';
        table += '<table><thead><tr>';
        table += '<th>Code</th><th>Description</th><th>Category</th><th>Quantity</th><th>Unit</th><th>Unit Price</th><th>Total</th>';
        table += '</tr></thead><tbody>';
        
        for (const item of items) {
            const itemTotal = (item.quantity || 0) * (item.unitPrice || 0);
            total += itemTotal;
            
            table += `<tr>
                <td>${item.code || '-'}</td>
                <td>${item.description || '-'}</td>
                <td>${item.category || '-'}</td>
                <td>${item.quantity || 0}</td>
                <td>${item.unit || '-'}</td>
                <td>${(item.unitPrice || 0).toFixed(2)}</td>
                <td><strong>${itemTotal.toFixed(2)}</strong></td>
            </tr>`;
        }
        
        table += `<tr style="background: #f0f0f0; font-weight: bold;">
            <td colspan="6" style="text-align: left;">GRAND TOTAL</td>
            <td>${total.toFixed(2)}</td>
        </tr>`;
        
        table += '</tbody></table>';
        return table;
    }
    
    generateTasksContent(tasks) {
        let table = '<h2>Tasks Report</h2>';
        table += '<table><thead><tr>';
        table += '<th>Title</th><th>Status</th><th>Priority</th><th>Assigned To</th><th>Progress</th><th>Due Date</th>';
        table += '</tr></thead><tbody>';
        
        for (const task of tasks) {
            const priorityClass = `status-${task.priority || 'low'}`;
            table += `<tr>
                <td>${task.title}</td>
                <td>${task.status || 'pending'}</td>
                <td><span class="status-badge ${priorityClass}">${task.priority || 'low'}</span></td>
                <td>${task.assignedTo || '-'}</td>
                <td>
                    <div style="background:#eee; border-radius:10px; overflow:hidden;">
                        <div style="background:#44aa44; width:${task.progress || 0}%; padding:2px; color:white; text-align:center; font-size:10px;">${task.progress || 0}%</div>
                    </div>
                </td>
                <td>${task.dueDate ? new Date(task.dueDate).toLocaleDateString() : '-'}</td>
            </tr>`;
        }
        
        table += '</tbody></table>';
        return table;
    }
    
    generateIssuesContent(issues) {
        let table = '<h2>Issues Report</h2>';
        table += '<table><thead><tr>';
        table += '<th>Title</th><th>Severity</th><th>Status</th><th>Reported By</th><th>Reported At</th>';
        table += '</tr></thead><tbody>';
        
        for (const issue of issues) {
            const severityClass = `status-${issue.severity || 'medium'}`;
            table += `<tr>
                <td>${issue.title}</td>
                <td><span class="status-badge ${severityClass}">${issue.severity || 'medium'}</span></td>
                <td>${issue.status || 'open'}</td>
                <td>${issue.reportedBy || '-'}</td>
                <td>${issue.reportedAt ? new Date(issue.reportedAt).toLocaleString() : '-'}</td>
            </tr>`;
        }
        
        table += '</tbody></table>';
        return table;
    }
    
    generateTableContent(data) {
        if (data.length === 0) return '<p>No data available</p>';
        
        const headers = Object.keys(data[0]);
        let table = '<table><thead><tr>';
        for (const header of headers) {
            table += `<th>${this.formatLabel(header)}</th>`;
        }
        table += '</tr></thead><tbody>';
        
        for (const row of data) {
            table += '<tr>';
            for (const header of headers) {
                const value = row[header];
                let displayValue = value;
                if (typeof value === 'object') displayValue = JSON.stringify(value);
                if (value === undefined || value === null) displayValue = '-';
                table += `<td>${displayValue}</td>`;
            }
            table += '</tr>';
        }
        
        table += '</tbody></table>';
        return table;
    }
    
    formatLabel(key) {
        const labels = {
            totalClashes: 'Total Clashes',
            highSeverity: 'High Severity',
            mediumSeverity: 'Medium Severity',
            lowSeverity: 'Low Severity',
            openIssues: 'Open Issues',
            completedTasks: 'Completed Tasks',
            pendingTasks: 'Pending Tasks',
            totalWorkers: 'Total Workers',
            activeWorkers: 'Active Workers'
        };
        return labels[key] || key.replace(/([A-Z])/g, ' $1').trim();
    }
    
    // ========== EXPORT OPTIONS ==========
    
    saveAsHTML(html, filename = 'report') {
        const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
        const link = document.createElement('a');
        const url = URL.createObjectURL(blob);
        
        link.href = url;
        link.setAttribute('download', `${filename}.html`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        
        console.log(`📄 HTML report saved: ${filename}.html`);
    }
    
    openInNewTab(html) {
        const newWindow = window.open();
        newWindow.document.write(html);
        newWindow.document.close();
    }
    
    registerTemplate(name, template) {
        this.templates.set(name, template);
    }
    
    exportWithTemplate(name, data, options = {}) {
        const template = this.templates.get(name);
        if (!template) {
            console.warn(`Template "${name}" not found`);
            return this.exportToHTML(data, options);
        }
        return this.exportToHTML(data, { ...options, template });
    }
    
    // ========== DISPOSE ==========
    
    dispose() {
        this.templates.clear();
        console.log('♻️ HTMLExporter disposed');
    }
}

export default HTMLExporter;